andywiecko/BurstTriangulator

- README.md
- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
Due to Unity internal error for `NativeList<T>` `AsDeferredJobArray().AsReadOnly()` is interpreted as empty array, even if list is fed in the previous job. The problem is resolved with [ReadOnly] attribute.
> fix: deferred array support

- README.md
- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
Input positions and holes can be transformed to normalized local coordinate system, i.e. [-1, 1] box. It could reduce numerical roundoff errors.
> feat: local transformation

- Runtime/Triangulator.cs
In this series of commits, a substantial refactor under the (grand-refactor) scope was carried out. To summarize, the key internal changes include:
- `TriangulatorNativeData` struct was removed;
- temporary buffers allocation was moved to jobs/utils;
- point-inserting methods were unified;
- miscellaneous changes simplifying the codebase.
> Native data grand-refactor

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
Substantial performance improvement for *classic* Delaunay triangulation (without refinement/constraints).
> perf: half-edge delaunay triangulation

- Runtime/Triangulator.cs
This commit prepares for `Triangle` struct removal.
> refactor: remove triangle methods

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This commit removes the 'pointsToRemove' and 'pointsOffsets' buffers to improve code organization. Additionally, it adds a new test case to verify the accuracy of the point removal logic.
> refactor: remove points cleanup buffers

- Runtime/Triangulator.cs
Miscellaneous code cleanup after refactor introduced @ 17c65ce..88b78bc
> refactor: misc cleanup

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This commit optimizes the refinement algorithm, making it more similar to Shewchuk's 'terminator' algorithm. In the next commit, we'll further enhance the refinement quality with changes inspired by the 'terminator' algorithm.
> refactor: refinement algorithm

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This commit enhances the quality of refinement in the resulting mesh. The generated triangles are now not uniform as before, with smaller ones created near boundaries and larger ones, not split, inside the bulk. Additionally, some parameters have been marked as obsolete, and a new parameter, `ConcentricShellParameter`, has been introduced in the triangulator settings. The `RefineJob` contract has been simplified and is no longer a generic job.
> refactor: increase refinement quality

- Runtime/Triangulator.cs
Refine mesh job cleanup after recent refactor.
> refactor: small refine mesh job cleanup

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This resolves GitHub issue #111.
> fix: point to halfedges during constraints

- README.md
- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
Add reqested `Verbose` feature in #120.
> feat: add verbose settings

- Runtime/Triangulator.cs
Remove dead code in the planting seed job. The condition `id >= initialPointsCount` is never satisfied. This dead code remained after a refactor that changed the order of refinement and hole planting. Previously, holes were planted after refinement, requiring some points to be removed. In the current implementation, where hole planting is done before refinement, no additional points need to be removed.
> refactor: remove dead code

- Runtime/Triangulator.cs
Introduce `Args` struct which will be used in further code cleanup and refactoring. Essentially this struct is struct version of `TriangulatorSettings` class. Currently, it is set as `private`.
> refactor: introduce args struct

- Runtime/Triangulator.cs
This commit introduces the internal `UnsafeTriangulator<T, T2, TU, TT>` struct, which will be used to introduce native support with a low-level API for triangulation.
> refactor: extract internal unsafe triangulator

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
- Tests/UnsafeTriangulatorEditorTests.cs
- Tests/UnsafeTriangulatorEditorTests.cs.meta
This commit introduces `UnsafeTriangulator<T>`, a low-level API for triangulation. Proper documentation will be added in the next commit.
> feat: public unsafe triangulator t

- Runtime/Triangulator.cs
- Tests/InternalUtilsTests.cs
- Tests/InternalUtilsTests.cs.meta
This commit addresses GitHub issue #173 by fixing the internal method `EdgeEdgeIntersection`. Additionally, it introduces tests for internal utilities and cleans up several utility implementations.
> fix: edge edge intersection gh issue #173

- Runtime/Triangulator.cs
Add comments/notes/TODOs for some internal methods. 
More notes are planned in the future.
> chore: add comments for internals

- Runtime/Triangulator.cs
- Tests/InternalUtilsTests.cs
Fix alpha calculations to support case when $d < D$. This commit adds unit test for method `alpha`.
> fix: alpha calculations

- Documentation~/manual/advanced/input-managed.md
- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
- Tests/UnsafeTriangulatorEditorTests.cs
> fix: as native array safty

- Tests/TestUtils.cs
Example assertion log:
```txt
Expected is <▲[2]: (6, 7, 8), ...>, actual is <▲[2]: (0, 1, 2), ...>.
Extra: <▲[2]: (0, 1, 2), ...>
Missing: <▲[2]: (6, 7, 8), ...>
```
> test: prettier triangles comparer

- Runtime/Triangulator.cs
Validation logs are now more detailed, displaying information about positions and constraints.
> feat: improve validation logs

- Runtime/Triangulator.cs
Caching `ProfileMarker`s can boost performance for triangulations with small input (~10² triangles).
> perf: profiler markers cache

- Runtime/Triangulator.cs
Fix potential issue with infinite loop during `PlantingSeedStep` with `AutoHolesAndBoundary`.
> fix: auto holes may stuck in loop

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
Added validations for input data and triangulation settings. Some validations result in warnings rather than errors. This improvement aims to assist beginner users by catching potential misconfigurations.
> feat: validate settings

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
This commit refactors the validation code by grouping related logic into distinct validation groups, improving structure and readability. This prepares also for introducing error flags.
> refactor: validation cleanup

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
Added new flags to the `Status` enum for improved error handling during triangulation. Users can now catch errors during validation. Note: `Status` is now decorated with the `Flags` attribute. To check if no errors occurred, compare using `status == Status.OK`.
> feat: status error codes

- Runtime/Triangulator.cs
> refactor: refinement internal methods

- Runtime/Triangulator.cs
> refactor: refinement internal methods (2)

- Runtime/Triangulator.cs
- Adds `UnsafeBowerWatson` internal helper struct used for point insertion.
> refactor: refinement internal methods (4)

- Runtime/Triangulator.cs
- Tests/TestUtils.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Test preview: ![image](https://github.com/user-attachments/assets/f6245552-8815-415d-af91-e56b74eed273)
Docs will be added in the future commits.
> feat: dynamic insert point

- Runtime/Triangulator.cs
Improves performance of triangle removal by approximately 25%, impacting mesh refinement and dynamic triangulation processes.
> perf: optimize bw triangles removal

- Runtime/Triangulator.cs
This commit improves triangle removal performance by approximately 2.5% in the planting seed step. Additionally, it reduces temporary memory allocation by eliminating the `map` buffer entirely.
> perf: optimize planting triangles removal

- Runtime/Triangulator.cs
Refactor `ProcessBadTriangles` in Bower-Watson algorithm, resulting in ~5% performance improvement for refinement and dynamic triangulation.
> perf: bw process bad triangles

- Runtime/Triangulator.cs
Removes a few redundant fields in refinement step and replaces it with `UnsafeBowerWatson bw` field.
> refactor: reduce tmp fields in refinement step

- Runtime/Triangulator.cs
Adds `tIdMinVisited` in Bower-Watson algorithm, which allows for removal BadTriangles sorting instruction.
> refactor: bw add tid min visited

- Runtime/Triangulator.cs
Removes `BadTriangles` buffer in Bower-Watson algorithm which reduces temporary allocation. Additionally improves performance for mesh refinement and dynamic triangulation.
> refactor: remove bad triangles in bw

- Runtime/Triangulator.cs
Unifies methods related to building triangles in Bower-Watson algorithm. Star and Amphitheater topology are now merged into single method with a proper comment.
> refactor: unify build triangles bw

- Runtime/Triangulator.cs
---
This commit fully replaces `NativeQueue<T>` with `NativeQueueList<T>`. Additionally, auto planting seeds algorithm is faster (increased performance by 3.5%).
> refactor: use native queue list in auto holes

- Runtime/Triangulator.cs
This change enhances performance by approximately ~50% during the refinement step. Previously, the `halfedges` and `triangles` queues were implemented using `NativeList<>`. This commit replaces `NativeList<>` with `NativeQueueList<>`, ensuring that adaptation of the queued elements is performed only for "not visited" elements.
Benchmarks demonstrating the performance improvements will be provided in subsequent commits.
> perf: faster refine mesh

- Runtime/Triangulator.cs
This is required for `ConstrainEdge` extension for `UnsafeTriangulator<T>`.
> feat: extract unsafe sloan

- Runtime/Triangulator.cs
- Tests/TestUtils.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Documentation will be included in the next commit.
> feat: constrain edge extension

- Runtime/Triangulator.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Note: docs and tests will be included in later commits.
> feat: alpha shape filter
