- Runtime/Triangulator.cs
The refactor replaces uniform `scale` with anisotropic one.
This is required for introducing PCA transformation algorithm.
> refactor: two component scale

- Runtime/Triangulator.cs
Cleanup some utils functions after recent `half-edges` introduction.
> refactor: utils cleanup

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This commit resolves a bug related to the Sloan algorithm. Prior to this fix, constraints tended to become stuck in "simple" cases. Additional test cases were added to address this issue.
> fix: sloan corner cases

- Runtime/Triangulator.cs
Move the allocation of `halfedges` from the job to `Triangulator`. This change is required to adapt other algorithms for the `halfedges` approach.
> refactor: extract halfedges list

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This commit refactors the constraint algorithm to utilize the `halfedges` approach.
This change has significantly improved performance. The algorithm no longer relies on triangulation mappings, such as edge-to-triangle and triangle-to-edge relationships (or circles). Additionally, the `satisfied` buffer has been removed. The complexity of the intersection searching algorithm has been reduced from a naive $\mathcal O(n^2)$ solution to $\mathcal O(n \log n)$.
---
Below one can find benchmark for v2.1+fix (1465c9e69cb712db78a5994ef5b9ef88933da6e4) and this HEAD (5b72114ff63783f4dd44ae2faa651460066dca8c). More detailed benchmark with explanation will be included in README.md before releasing `v2.2`.
> refactor: adapt constraint to halfedges

- Runtime/Triangulator.cs
Fix the sign in `CleanupJob` with respect to `pointsOffset` introduced @c8a20bf.
> fix: point offset sign

- Runtime/Triangulator.cs
This commit applies the `[MethodImpl(MethodImplOptions.AggressiveInlining)]` attribute to optimize the performance of the refinement job, achieving a 50% performance boost without any extra cost. The Burst compiler did better optimization for the given IL generated code.
> perf: add aggressive inlining attribute

- Runtime/Triangulator.cs
In some rare cases the result bad triangles could contain duplicates.
> fix: recalculate bad triangles

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This commit significantly improves the performance of the refinement job. However, the introduced buffer for constrained halfedges should be implemented in other jobs as well.
> perf: refinement constrained halfedges

- Runtime/Triangulator.cs
This PR refactors the package a bit.
The primary changes are:
* Changes the triangulator to schedule a single job, instead of multiple smaller ones. Since all previous jobs depended on each other in sequence, there was no benefit to scheduling smaller jobs, and it made resource management harder. Now, temporary arrays can be created using the Temp allocator. Performance wise, this is no significant change. It might be a bit faster, but I haven't done any extensive analysis. I'm planning to use this to triangulate *a lot* of meshes that have a very low point count, and then more jobs might very well have caused significant overhead. Mostly I did this to make the code shorter and clearer, though.
* The preprocessor transformations code has been greatly simplified. All transformations are …
> Reduce code complexity

- Documentation~/images/manual-halfedges.svg
- Documentation~/manual/advanced/output-halfedges.md
- Documentation~/manual/toc.yml
- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
This commit makes `Halfedges` available as additional output data. This mapping can be used by advanced users. My main motivation is to prepare package addon with path-finding utilities for tri-meshes.
> feat: make halfedges public

- Runtime/Triangulator.cs
Remove obsolete properties from `TriangulatorSettings`:
- `BatchCount`;
- `MinimumAngle`;
- `MinimumArea`;
- `MaximumArea`;
- `ConstrainEdges`.
> refactor!: remove obsoletes

- Runtime/Triangulator.cs
- Tests/TriangulatorEditorTests.cs
- This commit introduces generics to `TriangulationJob<...>`, enabling  the implementation of `Triangulator<T>` in the future.
- It adds an interface for utilities `IUtils<T, T2>` and an interface for transformations `ITransformation<TSelf, T, T2>` with default implementations for single precision `float`s: `FloatUtils` and `AffineTransform32`, respectively.
- Additionally, the `Circle` struct is hidden in the refinement step and other utilities are based on `Circle.RadiusSq` instead of `Circle.Radius`, which should result in better float approximation.
---
For the next commits, the plan is to introduce `DoubleUtils`, `AffineTransform64`, and finally `Triangulator<T>`.
> feat: introduce generics for coordinates

- Runtime/Triangulator.cs
- Tests/TestUtils.cs
- Tests/TriangulatorDouble2EditorTests.cs
- Tests/TriangulatorDouble2EditorTests.cs.meta
Add support for `double2` in `Triangulator<T2>`:
- Add `DoubleUtils : IUtils<double, double2>`.
- Add `AffineTransform64`.
- Add extension methods `Run` and `Schedule`.
- Add (copy) unit tests.
> feat: add double2 support

- README.md
The Unicode character ⤴ was rendered as an emoji instead of a character, so it has been replaced with ↗.
> docs: readme manual links (fixup)

- Runtime/Triangulator.cs
Since `distance` cannot be implemented for integer coordinates.
> refactor: simplify code to not require IUtils.distance

- Tests/TestUtils.cs
- Tests/TriangulatorGenericsEditorTests.cs
Add `TrianglesComparer` to facilitate triangle assertions. For example:
```csharp
Assert.That(output.Triangles.AsArray(), Is.EqualTo(expected).Using(TrianglesComparer.Instance));
```
This comparer sorts triangles internally, so (1, 2, 3) and (3, 1, 2) are considered equivalent.
Additionally, remove the `GetTrisTuple` extension methods and `SortTrianglesIds` utility.
> test: triangles comparer

- Runtime/Triangulator.cs
- Tests/InternalUtilsTests.cs
- Tests/TestUtils.cs
- Tests/TriangulatorEditorTests.cs
- Tests/TriangulatorGenericsEditorTests.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Here I am again with integer support.
I figured it was best to open a new PR, since the old one is very different at this point.
Support:
All tests pass except:
* PCA transformations
* Mesh refinement
I have modified some tests to only have one unambiguous solution. Previously the integer and float code picked different, but equally valid, solutions to some tests.
There are two new generic types:
* TSquare: Used for squared distances and multiplication results. The integer implementation needs this to be able to use `long`s to avoid overflow.
* TFloat: Used for angles and other unitless fractional values.
The local transform is supported, but it only supports translations. No scaling or rotation. Those are inappropriate for integer coordinates anyway. Even offsets shouldn't really be used …
> feat: support for integer coordinates

- Documentation~/manual/advanced/generic-coordinates.md
- Documentation~/unity-xrefmap.yml
- Runtime/Triangulator.cs
- Tests/TestUtils.cs
- Tests/TriangulatorGenericsEditorTests.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Add `Vector2` support as a triangulation coordinate type. It is implemented via `float2` reinterpretation.
> feat: add vector2 support

- Runtime/Triangulator.cs
- Tests/TestUtils.cs
- Tests/TriangulatorGenericsEditorTests.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Add support for triangulation using the `fp2` type (fixed-point representation in Q31.32 format). The `fp2` implementation is sourced as an optional dependency from the project: https://github.com/danielmansson/Unity.Mathematics.FixedPoint. Documentation and benchmarks will be added in future PRs.
> feat: triangulation support with fixed-point arithmetic

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
`Unity.Collections@2+` introduced a change in how it handles errors like `A Native Collection has not been disposed, resulting in a memory leak.` These memory leaks are now less noisy and require extra attention to manage. I'll need to consider how to incorporate these checks into the test suite.
> fix: missing dispose for temp data

- Tests/Runtime.meta
- Tests/Runtime/RuntimeDemo.cs
- Tests/Runtime/RuntimeDemo.cs.meta
- Tests/Runtime/RuntimeDemo.shader
- Tests/Runtime/RuntimeDemo.shader.meta
- Tests/Runtime/RuntimeDemoTest.cs
- Tests/Runtime/RuntimeDemoTest.cs.meta
- Tests/Runtime/RuntimeDemoTest.unity
- Tests/Runtime/RuntimeDemoTest.unity.meta
- Tests/Runtime/andywiecko.BurstTriangulator.Tests.Runtime.asmdef
- Tests/Runtime/andywiecko.BurstTriangulator.Tests.Runtime.asmdef.meta
This commit adds `RuntimeDemoTest` (classic triangulation of random points).
It will be included in CI test suite in the next commits.
https://github.com/user-attachments/assets/da5ac8ff-7ec3-4cbf-8a90-6af73b7080fb
> test: add runtime demo

- Documentation~/demo/index.md
Note: there is a new subpage in docs where one can check the basic capabilities of the package, see https://andywiecko.github.io/BurstTriangulator/demo
> docs: add demo info

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Previously, refinement was not working correctly with constraints without restoring the boundaries. The constraints were ignored when these options were selected.
> fix: refinement with constraints without holes

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
Fixed an issue where refinement could produce invalid results in rare cases, particularly when the input contains subsegment clusters. These invalid cases manifested with addition of points outside the triangulation domain.
<br>
> fix: refinement produces invalid result

- Runtime/Triangulator.cs
> refactor: refinement internal methods (3)

- Runtime/Triangulator.cs
- `Circles` buffer is now optional in `UnsafeBowerWatson`.
> refactor: refinement internal methods (5)

- Runtime/Triangulator.cs
Simplifies `Extensions` for `UnsafeTriangulator`.
Additionally fix threshold parameter for `UnsafeTriangulator<Vector2>.RefineMesh(...)`
> refactor: simplify unsafe extensions

- Tests/TriangulatorBenchmarkTests.cs
Add a benchmark test using Lake Superior as input, providing a more generalized test case compared to the previous refinement benchmark.
> test: refine lake benchmark

- Runtime/Triangulator.cs
Refactor and optimize queue adaptation in refinement step (likely negligible impact on performance).
```asm
lea               eax, [rdx + 2*rdx]
cmp               eax, ecx
sete              r8b
lea               eax, [rdx + 2*rdx + 1]
cmp               eax, ecx
sete              al
lea               edx, [rdx + 2*rdx + 2]
cmp               edx, ecx
sete              cl
or                cl, al
or                cl, r8b
movzx             eax, cl
```
```asm
movsxd            rax, ecx
imul              rcx, rax, 1431655766
mov               rax, rcx
shr               rax, 63
shr               rcx, 32
add               ecx, eax
xor               eax, eax
cmp               ecx, edx
sete              al
```
> refactor: slightly faster queue adaptation

- Runtime/Triangulator.cs
Optimized code for polygon construction in the Bower-Watson point insertion algorithm. Enhanced performance by replacing `NativeList.Contains` with direct indexing using `NativeArray[]`.
> refactor: bw build polygon

- Runtime/Triangulator.cs
Moves `heQueue` and `tQueue` adaptations directly into the Bower-Watson algorithm, removing them from the refinement step. This change lays the groundwork for removing the `BadTriangles` buffer. Additionally, it improves mesh refinement and dynamic triangulation performance by approximately 2%.
> refactor: adapt refinement queues in bw

- Runtime/Triangulator.cs
- Tests/TestUtils.cs
- Tests/UnsafeTriangulatorEditorTests.cs
Add extension for dynamic triangulation to support bulk point removal.
> feat: dynamic remove bulk point

- Runtime/Triangulator.cs
- Tests/InternalUtilsTests.cs
Renames internal utility implementations following the pattern: `TypeUtils -> UtilsType`, where `Type` is one of `Float`, `Double`, `Int`, or `Fp`. This naming convention aligns with `TransformType` implementations and improves IDE usability by making it easier to search for `Utils...` instead of `Type...`.
> refactor: rename internal utils

- Documentation~/docfx.json
Support for the `AllowUnsafeBlocks` field was introduced in DocFX version 2.78. This field is required to suppress warnings during documentation compilation.
> docs: update docfx json

- Runtime/Triangulator.cs
- Tests/InternalUtilsTests.cs
Introduce (internal) a custom `NativeQueueList<T>` implementation based on `NativeList<T>`, replacing the `com.unity.collections` `NativeQueue<T>` due to persistent bugs in Unity's implementation. This custom implementation offers significantly faster allocation and manipulation performance, though it is more memory-intensive. It will be incorporated in future commits to replace existing uses of `NativeQueue` throughout the codebase.
> feat: native queue list

- .github/workflows/build.yml
- .github/workflows/test.yml
`actions/cache@v2` will be deprecated soon!
> ci: update actions/cache@v3

- Runtime/Triangulator.cs
- Tests/TriangulatorGenericsEditorTests.cs
Introduced with `Utilities.BoundingBox`.
> fix: support for empty positions with preprocessors
